### ISSUE TITLE
Bot Does Not Go Online

### ISSUE THREAD

**Issue by BFB2q** [SinisterDeveloper/discord-moderation-bot#6]
I did all of the steps you showed but when i do node . it doesnt put thr bot online please help. I added you on discord :Sleepy Bear#0009

**Comment by BFB2q** [comment]
Neveer mid just had to do it in CMD not in terminal

**Comment by SinisterDeveloper** [comment]
It depends on how you configured NodeJS when installing yeah, if you have any more problems or require further assistance regarding anything else, you can let me know
