### ISSUE TITLE
Mongoose URL

### ISSUE THREAD

**Issue by aestriex** [SinisterDeveloper/discord-moderation-bot#8]
I don't fully understand how exactly do get the Mongoose uri even with the guide you linked, is there any ody who came explain further please?

**Comment by SinisterDeveloper** [comment]
- [ ] Create a MongoDB cluster at: https://www.mongodb.com/cloud/atlas
- [ ] On the homepage of cluster, click on `connect`
- [ ] Click on: `Connect your application` and copy the connection string
- [ ] Go to `Database Access` on cluster homepage and add a new user
- [ ] Replace `<user>` and `<password>` in your connection string with the new User credentials you have created

The connection string is your Mongodb connection uri 👍🏼

**Comment by aestriex** [comment]
Resolved
