### ISSUE TITLE
Typo on Class Kick.js

### ISSUE THREAD

**Issue by aestriex** [SinisterDeveloper/discord-moderation-bot#9]
**Describe the bug**
There is a typo within the code for the `kick.js` file.

**To Reproduce**
1. Go to `moderation/kick.js`
2. Scroll down to configuration description. 

**Expected behavior**
Expected to have the description say "Kick a user from the server.", instead shows `miscellaneous/ping.js` description.

**Comment by SinisterDeveloper** [comment]
Fixed
